export const WORKFLOW_STEPS = [
  {
    step: 1,
    title: "Harvest Vacant Positions",
    phase: "Phase 1",
    role: "hrmo",
    action: "Harvest Vacancies",
  },
  {
    step: 2,
    title: "Publish Vacancies",
    phase: "Phase 1",
    role: "hrmo",
    action: "Publish",
  },
  {
    step: 3,
    title: "Receipt of Applications",
    phase: "Phase 1",
    role: "records",
    action: "Acknowledge Application",
  },
  {
    step: 4,
    title: "Screen Applicants",
    phase: "Phase 2",
    role: "adas",
    action: "Shortlist Applicant",
  },
  {
    step: 5,
    title: "Initial Evaluation",
    phase: "Phase 2",
    role: "hrmpsb",
    action: "Generate Official List",
  },
  {
    step: 6,
    title: "Selection Process",
    phase: "Phase 2",
    role: "hrmpsb",
    action: "Interview & Exam",
  },
  {
    step: 7,
    title: "Consolidate Scores",
    phase: "Phase 2",
    role: "adas",
    action: "Rate Scoresheets",
  },
  {
    step: 8,
    title: "Deliberation Report",
    phase: "Phase 2",
    role: "hrmo",
    action: "Prepare Report",
  },
  {
    step: 9,
    title: "Prepare Reports",
    phase: "Phase 2",
    role: "hrmpsb",
    action: "Sign Report",
  },
  {
    step: 10,
    title: "Final Evaluation",
    phase: "Phase 3",
    role: "Superintendent",
    action: "Background Check & Advise",
  },
  {
    step: 11,
    title: "Prepare Appointment",
    phase: "Phase 4",
    role: "hrmo",
    action: "Draft Appointment",
  },
  {
    step: 12,
    title: "Review Completeness",
    phase: "Phase 4",
    role: "hrmo",
    action: "Submit to CSC",
  },
  {
    step: 13,
    title: "CSC Office",
    phase: "Phase 4",
    role: "csc",
    action: "Act on Appointment",
  },
  {
    step: 14,
    title: "Furnish Appointment",
    phase: "Phase 5",
    role: "records",
    action: "Furnish & Post",
  },
  {
    step: 15,
    title: "Encode Personnel",
    phase: "Phase 5",
    role: "hrmo",
    action: "Update System",
  },
];

export const getStepByNumber = (step: number) =>
  WORKFLOW_STEPS.find((s) => s.step === step);
